version: 2.1
jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: success
          command: |
            exit 0

workflows:
  version: 2
  test:
    jobs:
      - test
