name: Get and dump Checks API (REST)
on: workflow_dispatch # manual

jobs:
  job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: read
    steps:
    - uses: 'actions/checkout@v3'
    - id: git
      name: get commit ref
      run: |
        git rev-parse HEAD^{commit}
        echo "::set-output name=commit_sha::$(git rev-parse HEAD^{commit})"
    - uses: actions/github-script@v6
      with:
        script: |
          const res = await github.rest.checks.listForRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "${{ github.sha }}",
          })
          console.log(JSON.stringify(res, null, "\t"))
