name: Get status checks
on:
  workflow_dispatch: # manual
  push:
    tags:
    - '*'

jobs:
  job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: read
      statuses: read
    steps:
    - uses: 'actions/checkout@v3'
    - uses: actions/github-script@v6
      with:
        script: |
          await require("./.github/workflows/graphql.js")({ context, github })
