name: Get and dump Rollup object (GraphQL)
on: workflow_dispatch # manual

jobs:
  job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: 'actions/checkout@v3'
    - id: git
      name: get commit ref
      run: |
        echo ${{ context.github.ref }}
        echo "::set-output name=commit_sha::$(git rev-parse HEAD^{commit})"
    - uses: actions/github-script@v6
      with:
        script: |
          await require("./.github/workflows/graphql.js")("${{ steps.git.outputs.commit_sha }}", { context, github })
