name: Get and dump Statuses API (REST)
on: workflow_dispatch # dispatch manually

jobs:
  job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: read
    steps:
    - uses: 'actions/checkout@v3'
    - uses: actions/github-script@v6
      with:
        script: |
          {
            console.log("== list ==")
            const res = await github.rest.repos.listCommitStatusesForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "${{ github.sha }}",
            })
            console.log(JSON.stringify(res, null, "\t"))
          }
          {
            console.log("== combined ==")
            const res = await github.rest.repos.getCombinedStatusForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "${{ github.sha }}",
            })
            console.log(JSON.stringify(res, null, "\t"))
          }
